In [1]:
#numpy es una libreria que permitirá trabajar con arreglos de una o más dimensiones de manera simple
import numpy as np# se importa la libreria completa de numpy baso el alias np
# en caso de no funcionar es necesario instalar la libreria
#pip install numpy
#conda install numpy

In [13]:
#crear un vector de 10 ceros
vector=np.zeros(10)#notese que los ceros son creados en formato float
print('vector',vector)
#crear una matriz de 2X4
matriz=np.zeros([2,4])
print(matriz)
#crear una matriz de 5X5 con valores aleatorios
print("********************")
matriz=np.random.random([5,5])#notar que los valores estan entre 0 y 1
print(matriz)
#crear una matriz de 5X5 con valores entre 1 y 100
print("********************")
matriz=np.random.random([5,5])*100
print(matriz)

vector [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
********************
[[0.24633673 0.08191148 0.95234844 0.74525371 0.57660037]
 [0.2786008  0.52199498 0.73036001 0.68870353 0.06430157]
 [0.14747953 0.35221493 0.98181417 0.55119891 0.54351354]
 [0.45749253 0.30061475 0.37632253 0.01824214 0.32127973]
 [0.52729387 0.57058835 0.12590958 0.52900243 0.88262857]]
********************
[[28.66042035  0.13705763 91.71906567 96.14405425 73.72276229]
 [91.54088612 30.37828069 33.85179778 16.68239196  6.10248471]
 [38.43773826  7.61153463 53.86807907 45.24614291 80.89228402]
 [82.13583904 87.68426217 45.372947   33.13313815 57.04648356]
 [11.8154442  82.19565349 67.50574351  5.16895171 54.58015655]]


In [16]:
#obtener datos del array
print(type(matriz))
print(matriz.shape)#obtiene las dimensiones

<class 'numpy.ndarray'>
(5, 5)


In [36]:
#suma de matrices. Es necesario que las dimensiones sean iguales
mt1=np.random.random([3,3])*10
#print(mt1)
mt2=np.random.random([3,3])*10
res=mt1+mt2
print(res)
print("**********************")
#la multiplicacion se realiza con escalares y matrices, en el cso de las matrices
#la cantidad de filas de la primera matriz debe ser igual a la cantidad de columnas de la segunda
mt1=np.array([[1,2,3,4],[6,7,8,3]])#matriz de 2X 4
mt2=np.array([[1,3],[5,7],[6,8],[8,3]])#matriz 4X2
print(mt1*2)
print("***********")
#print(mt2*mt1)

[[14.54322644 15.91340052  9.72185258]
 [ 8.53355303  1.73628937  9.91950417]
 [12.06703134  8.581583   15.3862792 ]]
**********************
[[ 2  4  6  8]
 [12 14 16  6]]
***********


ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 

In [48]:
#acceso a filas o columnas
print(mt1[:,0])#muestra la primera columna
print(mt1[0,:])#muestra la primera fila

[1 6]
[1 2 3 4]


In [56]:
#con numpy es posible trabajar usando mascaras que permitan filtrar contenidos

matriz=np.random.random([5,6])*100
masc=matriz>70
print(matriz)
print("*******************")
print(matriz[masc])#sólo imprime los vares que cumplen con la condición

[[86.45220471 42.6462472  79.94607526 46.7449795  12.62243379 57.44411989]
 [68.08218111 97.19246167  9.53124237 32.68209951 88.8248434   2.45687352]
 [52.52539456 84.40180475 48.44772821 29.38213705 63.167065   97.89111284]
 [71.91966212 70.35069673 67.29858638 12.17461086 28.05768981 45.35503276]
 [98.73667807 35.11918488 58.47842559 25.88166737 33.26169086 43.07048464]]
*******************
[86.45220471 79.94607526 97.19246167 88.8248434  84.40180475 97.89111284
 71.91966212 70.35069673 98.73667807]


In [58]:
#sumar los valores de una fila
print(np.sum(matriz,axis=1))
#sumar valores de las columnas
print(np.sum(matriz,axis=0))

[325.85606035 298.76970157 375.8152424  295.15627866 294.54813143]
[377.71612057 329.71039524 263.70205781 146.86549428 225.93372287
 246.21762364]


In [59]:
#matriz transpuesta
transpuesta=matriz.T
print(transpuesta)

[[86.45220471 68.08218111 52.52539456 71.91966212 98.73667807]
 [42.6462472  97.19246167 84.40180475 70.35069673 35.11918488]
 [79.94607526  9.53124237 48.44772821 67.29858638 58.47842559]
 [46.7449795  32.68209951 29.38213705 12.17461086 25.88166737]
 [12.62243379 88.8248434  63.167065   28.05768981 33.26169086]
 [57.44411989  2.45687352 97.89111284 45.35503276 43.07048464]]


In [67]:
#obtener promedio y desviación estandar de un conjunto de datos
data=(np.random.random(1000))#generar un vector de mil datos
print(np.mean(data))
print (np.std(data))
print(data)

0.4829965249276995
0.28618957916955723
[9.32545990e-01 4.04212757e-01 1.41953671e-02 2.72639376e-01
 1.10853582e-01 7.46874131e-01 4.87500270e-01 4.44435077e-01
 3.19200923e-01 4.47662058e-01 5.27638733e-01 1.02220961e-01
 8.99262686e-01 8.19221327e-01 4.98054449e-01 8.26307318e-01
 6.47710380e-02 4.95614687e-01 2.27545446e-01 2.86930024e-02
 8.70798365e-01 8.65643785e-01 5.00835471e-01 8.08388474e-01
 2.37422434e-01 1.09394969e-02 2.06178215e-01 5.04959852e-01
 9.23916659e-01 4.64694043e-01 9.30458581e-01 5.54812262e-01
 9.94641275e-01 7.56275373e-01 9.89576640e-01 3.23463435e-01
 3.79920284e-02 4.80807548e-01 8.32227646e-01 9.40565383e-02
 7.56218715e-01 6.00998379e-01 6.73701867e-01 4.33161413e-01
 7.96113985e-01 4.55000522e-01 6.71663255e-01 6.33189495e-01
 1.15206404e-01 4.06449462e-01 4.84048096e-01 1.46206517e-01
 5.30513192e-01 2.01365959e-01 7.72601153e-01 1.51806426e-01
 1.01975602e-01 7.87479387e-01 2.77282932e-01 4.61579776e-01
 2.43170563e-01 1.24984208e-01 4.85126272e-01 

In [69]:
#arreglos con valores entre 0 y y un valor
vector=np.arange(0,9)#del 0 al 8
print(vector)

[0 1 2 3 4 5 6 7 8]
